name: MTweet
version: ${version}
main: com.github.snowpegeon.mtweet.MTweetPlugin
description: MTweet plugin can Tweet for Minecraft.
author: snow_pegeon
api-version: '1.21'
website: https://github.com/snowpegeon/MTweet
commands:
  mtweet:
    usage: /mtweet Message
permissions:
  mtweet.*:
    default: op